[package]
name = "wasmppt-opc"
description = "Bounded Open Packaging Conventions and ZIP substrate for wasmppt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[features]
default = []

[dependencies]
crc32fast.workspace = true
flate2.workspace = true
wasmppt-xml.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
