/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 712a59d8cde7bd4645403d683da44084)
interface __BaseEnv_Env {
	TEMPLATES: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
